rules:
  - type: percentage
    values:
      - chance: 50
        url: https://778p6776.optimalworkshop.com/treejack/ksbymk78
      - chance: 50
        url: https://778p6776.optimalworkshop.com/treejack/84626swy
