rules:
  - type: percentage
    values:
      - chance: 10
        url: https://example.com#A
      - chance: 10
        url: https://example.com#B
      - chance: 10
        url: https://example.com#C
