rules:
  - type: percentage
    values:
      - chance: 50
        url: https://778p6776.optimalworkshop.com/optimalsort/nhs-uk-card-sort-a
      - chance: 50
        url: https://778p6776.optimalworkshop.com/optimalsort/nhs-uk-card-sort-b
